# 🛃 Гаалийн импортын мэдүүлэг — pandas дасгал / 관세 수입신고 데이터 pandas 실습

**Өгөгдөл / 데이터:** `customs_imports_2024.csv` (30,000 мэдүүлэг / 신고 3만 건, 2024-01-01 ~ 02-26)

**Зорилго / 목표:** pandas-ийн үндсэн **нэгтгэл ба цэвэрлэгээ**-г гараараа бичиж сурах · ~2 цаг / 약 2시간

**Заавар / 사용법:** Асуулт бүрийн доорх **хоосон нүдэнд** өөрөө код бичиж ажиллуул. Гацвал асуулт дахь 💡 зөвлөмжийг хар. Хариултыг багш дараа тусад нь өгнө.
각 문제 아래 **빈 코드 셀**에 직접 작성해 실행하세요. 막히면 💡 힌트를 보고, 정답은 나중에 따로 받습니다.

| Багана / 컬럼 | Утга (МН) | 의미 (KR) |
|---|---|---|
| `decl_no` / `decl_date` | мэдүүлгийн дугаар / огноо | 신고번호 / 신고일자 |
| `customs_office` / `decl_type` | гаалийн газар / мэдүүлгийн төрөл | 세관코드 / 신고유형 |
| `item_count` / `incoterms` | барааны тоо / худалдааны нөхцөл | 품목 수 / 인코텀즈 |
| `broker` / `currency` | зуучлагч / валют | 관세사 / 결제통화 |
| `pay_amount` / `exch_rate` | төлбөрийн дүн / ханш | 결제금액 / 환율 |
| `stat_value` / `duty_amount` | статистик үнэ / гаалийн татвар | 과세가격 / 관세액 |
| `origin_country` / `contract_country` | гарал үүслийн улс / гэрээний улс | 원산지 / 계약국 |

---

## Part 0. Өгөгдөл унших ба ажиглах / 데이터 불러오기 & 살펴보기

**МН:** Дата шинжилгээний эхний алхам бол **өгөгдлийг уншиж, бүтцийг нь ойлгох** явдал юм. Ямар багана байгаа, хэдэн мөртэй, багана бүр ямар төрөлтэй (тоо / текст / огноо) болохыг эхлээд шалгаарай.

**КО:** 데이터 분석의 첫걸음은 **데이터를 불러오고 생김새를 파악하는 것**입니다. 어떤 컬럼이 있고, 몇 행인지, 각 컬럼의 자료형(숫자/문자/날짜)이 무엇인지 먼저 확인하세요.

### T0-1.
**МН:** pandas-ийг `pd` нэрээр импортлоод, CSV файлыг `df` болгон уншиж, эхний 5 мөрийг хэвлэ.

**КО:** pandas를 `pd`로 불러오고, CSV를 `df`로 읽은 뒤 상위 5행을 출력하세요.

> 💡 `pd.read_csv(...)`, `df.head()`

In [11]:
import pandas as pd
import matplotlib.pyplot as plt 

df = pd.read_csv("customs_imports_2024.csv")
df.head(5)

,decl_no,customs_office,decl_type,item_count,incoterms,broker,currency,pay_amount,exch_rate,stat_value,duty_amount,origin_country,contract_country,decl_date
0,04213100724I30000,4200,400,1,EXW,Broker_045,EUR,2100.0,3791.66,2439.567,1.289694e+06,DE,DE,2024-01-01
1,02215101524I30000,2222,400,1,FOB,Broker_006,JPY,217000.0,24.22,2592.719,7.805659e+06,JP,JP,2024-01-01
2,02111013224I00007,2222,451,1,CPT,Broker_074,JPY,7458000.0,24.22,52960.767,3.647602e+07,JP,JP,2024-01-02
3,02209100624I30018,2222,400,1,FOB,Broker_032,JPY,500000.0,24.22,4714.173,8.927181e+06,JP,JP,2024-01-02
4,02214100424I30131,2222,400,1,FCA,Broker_005,CNY,162000.0,480.01,23893.751,8.149418e+06,CN,CN,2024-01-02

### T0-2.
**МН:** Энэ өгөгдөл хэдэн мөр, хэдэн баганатай вэ? Баганануудын нэрсийн жагсаалтыг мөн хэвлэ.

**КО:** 이 데이터는 몇 행 몇 열인가요? 컬럼 이름 목록도 출력하세요.

> 💡 `df.shape`, `df.columns`

In [13]:
print("shape " , df.shape)
print("colums" , df.columns)

shape  (30000, 14)
colums Index(['decl_no', 'customs_office', 'decl_type', 'item_count', 'incoterms',
       'broker', 'currency', 'pay_amount', 'exch_rate', 'stat_value',
       'duty_amount', 'origin_country', 'contract_country', 'decl_date'],
      dtype='str')

### T0-3.
**МН:** Багана бүрийн өгөгдлийн төрлийг шалга. Аль багана нь тоо, аль нь текст вэ?

**КО:** 각 컬럼의 자료형을 확인하세요. 어떤 컬럼이 숫자이고 어떤 게 문자인가요?

> 💡 `df.dtypes` / `df.info()`

In [16]:
print(df.dtypes)
print(df.info)

decl_no                 str
customs_office        int64
decl_type             int64
item_count            int64
incoterms               str
broker                  str
currency                str
pay_amount          float64
exch_rate           float64
stat_value          float64
duty_amount         float64
origin_country          str
contract_country        str
decl_date               str
dtype: object
<bound method DataFrame.info of                  decl_no  customs_office  decl_type  item_count incoterms  \
0      04213100724I30000            4200        400           1       EXW
1      02215101524I30000            2222        400           1       FOB
2      02111013224I00007            2222        451           1       CPT
3      02209100624I30018            2222        400           1       FOB
4      02214100424I30131            2222        400           1       FCA
...                  ...             ...        ...         ...       ...
29995  05071347824I00013            5904        400          14       CIP
29996  04201082124I00001            4912        400           2       FCA
29997  03211100524I30234            3904        400           9       FCA
29998  02221102224I30608            2222        400           2       CPT
29999  02213100624I31902            2222        400           1       DAP

           broker currency  pay_amount  exch_rate  stat_value   duty_amount  \
0      Broker_045      EUR      2100.0    3791.66    2439.567  1.289694e+06
1      Broker_006      JPY    217000.0      24.22    2592.719  7.805659e+06
2      Broker_074      JPY   7458000.0      24.22   52960.767  3.647602e+07
3      Broker_032      JPY    500000.0      24.22    4714.173  8.927181e+06
4      Broker_005      CNY    162000.0     480.01   23893.751  8.149418e+06
...           ...      ...         ...        ...         ...           ...
29995  Broker_082      USD     28836.1    3386.98   28836.100  9.766729e+06
29996  Broker_182      EUR      4149.0    3667.76    4709.531  2.472419e+06
29997  Broker_015      USD      5203.0    3386.98    8014.260  4.207341e+06
29998  Broker_024      RUB   1109393.6      36.42   11929.245  6.262638e+06
29999  Broker_007      RUB    674250.0      36.42    7250.171  3.806209e+06

      origin_country contract_country   decl_date
0                 DE               DE  2024-01-01
1                 JP               JP  2024-01-01
2                 JP               JP  2024-01-02
3                 JP               JP  2024-01-02
4                 CN               CN  2024-01-02
...              ...              ...         ...
29995             SG               SG  2024-02-26
29996             DK               DK  2024-02-26
29997             CN               CN  2024-02-26
29998             RU               RU  2024-02-26
29999             RU               RU  2024-02-26

[30000 rows x 14 columns]>

### T0-4.
**МН:** Тоон баганануудын үндсэн статистик (дундаж, хамгийн бага, их г.м)-ийг нэг дор гаргаж үз.

**КО:** 숫자형 컬럼들의 기초 통계(평균·최소·최대 등)를 한 번에 요약해 보세요.

> 💡 `df.describe()`

In [17]:
print(df.describe)

<bound method NDFrame.describe of                  decl_no  customs_office  decl_type  item_count incoterms  \
0      04213100724I30000            4200        400           1       EXW
1      02215101524I30000            2222        400           1       FOB
2      02111013224I00007            2222        451           1       CPT
3      02209100624I30018            2222        400           1       FOB
4      02214100424I30131            2222        400           1       FCA
...                  ...             ...        ...         ...       ...
29995  05071347824I00013            5904        400          14       CIP
29996  04201082124I00001            4912        400           2       FCA
29997  03211100524I30234            3904        400           9       FCA
29998  02221102224I30608            2222        400           2       CPT
29999  02213100624I31902            2222        400           1       DAP

           broker currency  pay_amount  exch_rate  stat_value   duty_amount  \
0      Broker_045      EUR      2100.0    3791.66    2439.567  1.289694e+06
1      Broker_006      JPY    217000.0      24.22    2592.719  7.805659e+06
2      Broker_074      JPY   7458000.0      24.22   52960.767  3.647602e+07
3      Broker_032      JPY    500000.0      24.22    4714.173  8.927181e+06
4      Broker_005      CNY    162000.0     480.01   23893.751  8.149418e+06
...           ...      ...         ...        ...         ...           ...
29995  Broker_082      USD     28836.1    3386.98   28836.100  9.766729e+06
29996  Broker_182      EUR      4149.0    3667.76    4709.531  2.472419e+06
29997  Broker_015      USD      5203.0    3386.98    8014.260  4.207341e+06
29998  Broker_024      RUB   1109393.6      36.42   11929.245  6.262638e+06
29999  Broker_007      RUB    674250.0      36.42    7250.171  3.806209e+06

      origin_country contract_country   decl_date
0                 DE               DE  2024-01-01
1                 JP               JP  2024-01-01
2                 JP               JP  2024-01-02
3                 JP               JP  2024-01-02
4                 CN               CN  2024-01-02
...              ...              ...         ...
29995             SG               SG  2024-02-26
29996             DK               DK  2024-02-26
29997             CN               CN  2024-02-26
29998             RU               RU  2024-02-26
29999             RU               RU  2024-02-26

[30000 rows x 14 columns]>

## Part 1. Өгөгдөл цэвэрлэх / 데이터 정제

**МН:** Бодит өгөгдөлд **дутуу утга, буруу төрөл, давхардал** холилддог. Шинжилгээ хийхээс өмнө эдгээрийг цэгцлэх дадал эзэмшинэ.

**КО:** 실무 데이터는 **결측치·잘못된 자료형·중복**이 섞여 있습니다. 분석 전에 이를 정리하는 습관을 들입니다.

### T1-1.
**МН:** Багана бүрийн дутуу (хоосон) утгын тоог тоол. Аль баганад дутуу утга байна вэ?

**КО:** 컬럼별 결측치(빈 값) 개수를 세어 보세요. 어떤 컬럼에 결측치가 있나요?

> 💡 `df.isnull().sum()`

In [21]:
df.isnull().sum()

decl_no              0
customs_office       0
decl_type            0
item_count           0
incoterms            0
broker               0
currency             0
pay_amount           0
exch_rate            0
stat_value           0
duty_amount          0
origin_country       0
contract_country    72
decl_date            0
dtype: int64

### T1-2.
**МН:** `contract_country` (гэрээний улс)-ын дутуу утгыг `origin_country` (гарал үүслийн улс)-ын утгаар нөхөөрэй. Дараа нь дутуу утга 0 болсныг шалга.

**КО:** `contract_country`(계약국)의 결측치를 `origin_country`(원산지) 값으로 채우세요. 처리 후 결측치가 0이 되는지 확인합니다.

> 💡 `df['contract_country'].fillna(df['origin_country'])`

In [22]:
df['contract_country'].fillna(df['origin_country'])

0        DE
1        JP
2        JP
3        JP
4        CN
         ..
29995    SG
29996    DK
29997    CN
29998    RU
29999    RU
Name: contract_country, Length: 30000, dtype: str

pd.to_datetime(...)`, `.dt.month

### T1-3.
**МН:** `decl_date` (мэдүүлгийн огноо) одоо текст хэлбэртэй байна. Үүнийг огнооны төрөлд хөрвүүлж, зөвхөн **сарыг (month)** гаргаж `month` шинэ багана нэм.

**КО:** `decl_date`(신고일자)는 지금 문자입니다. 날짜형으로 바꾸고, 신고한 **월(month)** 만 뽑아 새 컬럼 `month`로 추가하세요.

> 💡 `pd.to_datetime(...)`, `.dt.month`

In [ ]:
pd.to_datetime().dt.month

SyntaxError: invalid syntax (2364465217.py, line 1)

### T1-4.
**МН:** `decl_no` (мэдүүлгийн дугаар) давхардсан мөр байгаа эсэхийг шалга. (байхгүй нь хэвийн)

**КО:** 신고번호 `decl_no`가 중복된 행이 있는지 확인하세요. (없는 게 정상)

> 💡 `df['decl_no'].duplicated().sum()`

In [24]:
df['decl_no'].duplicated().sum()

np.int64(0)

## Part 2. Сонгох ба шүүх / 선택 & 필터링

**МН:** Хүссэн **баганаа сонгож**, нөхцөлд тохирсон **мөрүүдийг шүүж авах** дасгал. Шинжилгээнд хамгийн их хэрэглэгддэг үйлдэл.

**КО:** 원하는 **열만 고르고**, 조건에 맞는 **행만 추리는** 연습입니다. 분석에서 가장 자주 쓰는 동작입니다.

### T2-1.
**МН:** `decl_no`, `currency`, `pay_amount`, `origin_country` гэсэн 4 баганыг л сонгож эхний 5 мөрийг үз.

**КО:** `decl_no`, `currency`, `pay_amount`, `origin_country` 네 컬럼만 골라 상위 5행을 보세요.

> 💡 `df[['col1','col2', ...]]`

In [28]:
df[["pay_amount" , "currency", "origin_country","decl_no"]].head()

   pay_amount currency origin_country            decl_no
0      2100.0      EUR             DE  04213100724I30000
1    217000.0      JPY             JP  02215101524I30000
2   7458000.0      JPY             JP  02111013224I00007
3    500000.0      JPY             JP  02209100624I30018
4    162000.0      CNY             CN  02214100424I30131

### T2-2.
**МН:** Төлбөрийн валют (`currency`) нь **USD** байх мэдүүлгүүдийг шүүж, тоог нь гаргаарай.

**КО:** 결제통화(`currency`)가 **USD**인 신고 건만 추리고, 그 건수를 세어 보세요.

> 💡 `df[df['currency'] == 'USD']`, `len(...)`

In [37]:
usd = df[df["currency"] == 'USD']
print("number" , len(usd))

number 8739

### T2-3.
**МН:** Гарал үүслийн улс нь **Япон (JP)** бөгөөд `stat_value` нь **10000-аас их** мэдүүлгүүдийг шүү.

**КО:** 원산지가 **일본(JP)** 이면서 과세가격 `stat_value`가 **10000 초과**인 건만 추리세요.

> 💡 нөхцөл хоёрыг `&`-ээр холбож, тус бүрийг хаалтанд / 조건 두 개는 `&`로 묶고 각 조건은 괄호로: `(a) & (b)`

In [48]:
stat1 = df.query(("origin_country == 'JP' and stat_value > 100000"))
print("result" , stat1)

result                  decl_no  customs_office  decl_type  item_count incoterms  \
2332   02209101024I30044            2222        400          33       FOB
3345   02214100224I30073            2222        400          20       CPT
3575   03209101724I30051            3907        451           1       FOB
4156   03209101724I30052            3907        451           1       FOB
5942   02211100424I30096            2222        400           1       CIP
7114   02213100624I30427            2222        700           1       CIP
7470   03212100124I30106            3907        700           1       FOB
9211   03224100124I30017            3907        700           1       FOB
10291  03215101724I30194            3907        400           1       CFR
10738  02213100224I30417            2222        400          10       FOB
12746  02224100124I30337            2222        400         420       CIF
13974  02224100124I30361            2222        400         179       CIF
14999  05209100824I30052            5904        400         106       CIP
15473  02224100124I30418            2222        400         353       CIF
16514  02224100124I30444            2222        400         154       CIF
20302  02216100124I31048            2222        400          18       FOB
21143  03212100124I30417            3907        400           1       CIF
21163  03212100124I30415            3907        400           1       CIF
21570  02209100824I30170            2222        500           1       CIF
22112  02209101024I30635            2222        400         561       CIP
22780  02223100324I30190            2222        400         447       CIF
23196  02211100524I30962            2222        400           2       FOB
23434  02209101024I30689            2222        400           6       FOB
24674  02223100324I30278            2222        400         447       CIF
25463  05209100824I30097            5904        400          72       CIP
25645  03212100124I30536            3907        400           1       CIF
27467  02213100624I31659            2222        700           1       CIP
27930  02213100224I31043            2222        400           8       FOB
29295  03212100124I30557            3907        400           1       FOB
29588  03211100524I30232            3913        400           1       CFR
29682  03211100524I30231            3907        400           1       CFR
29861  03209101724I30691            3913        400           1       FOB
29924  03223100324I30044            3907        700           1       FOB

           broker currency   pay_amount  exch_rate  stat_value   duty_amount  \
2332   Broker_021      JPY  16507161.00      24.09  117271.453  6.199055e+07
3345   Broker_027      JPY  27313469.00      23.95  191792.887  1.013944e+08
3575   Broker_029      JPY  79460000.00      23.78  638651.594  2.177304e+08
4156   Broker_029      JPY  79460000.00      23.78  643704.120  2.194529e+08
5942   Broker_022      JPY  26400000.00      23.61  187459.546  6.391227e+07
7114   Broker_007      USD    323328.00    3409.39  323328.000  0.000000e+00
7470   Broker_037      JPY  49820000.00      23.52  372946.903  0.000000e+00
9211   Broker_012      JPY  49820000.00      23.49  385611.740  0.000000e+00
10291  Broker_014      JPY  85415233.00      23.44  601239.122  2.049865e+08
10738  Broker_019      USD    131607.20    3409.40  139207.208  7.356502e+07
12746  Broker_012      USD    230647.43    3406.48  235142.764  1.241564e+08
13974  Broker_012      USD    142680.44    3406.51  144721.932  7.641449e+07
14999  Broker_009      USD    100130.26    3407.14  100130.260  5.287946e+07
15473  Broker_012      USD    185400.03    3406.83  187847.296  9.919439e+07
16514  Broker_012      USD    109885.39    3406.96  111715.422  5.851684e+07
20302  Broker_004      JPY  16556408.00      23.04  115043.383  6.065408e+07
21143  Broker_037      JPY  43198860.00      23.19  305386.977  1.038438e+08
21163  Broker_037      USD    152648.40    3400.40  162148.400  5.513694e+07
21570  Broker_009      JPY  24427500.00      23.19  169128.530  9.667705e+07
22112  Broker_021      JPY  18516721.00      23.19  126280.077  6.655743e+07
22780  Broker_012      USD    213034.61    3399.82  215380.080  1.134887e+08
23196  Broker_015      USD    142047.00    3399.82  230447.000  7.834783e+07
23434  Broker_021      JPY  16659540.00      22.88  114317.411  6.020594e+07
24674  Broker_012      USD    128944.83    3397.47  129807.478  6.835763e+07
25463  Broker_009      USD    165257.71    3395.09  165257.710  8.696504e+07
25645  Broker_037      USD    284095.08    3394.91  298945.080  1.014892e+08
27467  Broker_007      USD    323328.00    3391.87  323328.000  0.000000e+00
27930  Broker_019      JPY  22265496.00      22.58  150611.281  7.918889e+07
29295  Broker_037      JPY  86430000.00      22.56  608432.539  2.061467e+08
29588  Broker_015      JPY  86098058.00      22.56  588054.939  1.991748e+08
29682  Broker_015      JPY  93911732.00      22.56  640139.587  2.168159e+08
29861  Broker_029      JPY  23560000.00      22.56  193459.305  6.552486e+07
29924  Broker_012      JPY  49820000.00      22.50  371738.882  0.000000e+00

      origin_country contract_country   decl_date
2332              JP               JP  2024-01-03
3345              JP               JP  2024-01-04
3575              JP               JP  2024-01-05
4156              JP               JP  2024-01-05
5942              JP               JP  2024-01-09
7114              JP               KZ  2024-01-10
7470              JP               JP  2024-01-11
9211              JP               JP  2024-01-15
10291             JP               JP  2024-01-16
10738             JP               JP  2024-01-16
12746             JP               JP  2024-01-19
13974             JP               JP  2024-01-22
14999             JP               JP  2024-01-23
15473             JP               JP  2024-01-24
16514             JP               JP  2024-01-25
20302             JP               JP  2024-02-01
21143             JP               JP  2024-02-03
21163             JP               JP  2024-02-03
21570             JP               JP  2024-02-05
22112             JP               JP  2024-02-05
22780             JP               JP  2024-02-06
23196             JP               JP  2024-02-06
23434             JP               JP  2024-02-07
24674             JP               JP  2024-02-08
25463             JP               JP  2024-02-13
25645             JP               JP  2024-02-14
27467             JP               KZ  2024-02-16
27930             JP               JP  2024-02-19
29295             JP               JP  2024-02-22
29588             JP               JP  2024-02-23
29682             JP               JP  2024-02-23
29861             JP               JP  2024-02-23
29924             JP               JP  2024-02-24

### T2-4.
**МН:** Гарал үүсэл нь Япон, Хятад, Солонгос (JP, CN, KR)-ийн аль нэг байх мэдүүлгүүдийг шүү.

**КО:** 원산지가 일본·중국·한국(JP, CN, KR) 중 하나인 건만 추리세요.

> 💡 `.isin([...])`

In [ ]:
asia = df[df["origin_country"].isin(["JP","CN","KR"])]
print(asia)

                 decl_no  customs_office  decl_type  item_count incoterms  \
1      02215101524I30000            2222        400           1       FOB
2      02111013224I00007            2222        451           1       CPT
3      02209100624I30018            2222        400           1       FOB
4      02214100424I30131            2222        400           1       FCA
5      02209102224I30144            2222        400           1       FOB
...                  ...             ...        ...         ...       ...
29986  03223100324I30049            3907        400           1       FCA
29987  03223100324I30048            3907        400          15       FCA
29988  03209100824I30745            3907        400           5       FCA
29994  03215100924I30595            3908        400           1       EXW
29997  03211100524I30234            3904        400           9       FCA

           broker currency  pay_amount  exch_rate  stat_value   duty_amount  \
1      Broker_006      JPY   217000.00      24.22    2592.719  7.805659e+06
2      Broker_074      JPY  7458000.00      24.22   52960.767  3.647602e+07
3      Broker_032      JPY   500000.00      24.22    4714.173  8.927181e+06
4      Broker_005      CNY   162000.00     480.01   23893.751  8.149418e+06
5      Broker_003      JPY   353000.00      24.22    3705.833  3.719114e+06
...           ...      ...         ...        ...         ...           ...
29986  Broker_012      CNY    25925.00     470.56    8026.048  4.213530e+06
29987  Broker_012      USD    14002.94    3386.98   19949.224  1.047298e+07
29988  Broker_009      CNY    49614.00     470.56    8109.355  4.257265e+06
29994  Broker_008      CNY   607860.00     470.56   89580.454  4.702812e+07
29997  Broker_015      USD     5203.00    3386.98    8014.260  4.207341e+06

      origin_country contract_country   decl_date
1                 JP               JP  2024-01-01
2                 JP               JP  2024-01-02
3                 JP               JP  2024-01-02
4                 CN               CN  2024-01-02
5                 JP               JP  2024-01-02
...              ...              ...         ...
29986             CN               CN  2024-02-25
29987             CN               CN  2024-02-25
29988             CN               CN  2024-02-25
29994             CN               CN  2024-02-26
29997             CN               CN  2024-02-26

[23294 rows x 14 columns]

## Part 3. Нэгтгэл / 집계 (Aggregation)

**МН:** Өгөгдлийг **бүлгээр нэгтгэн нийлбэр, дундаж, тоог** гаргах — шинжилгээний гол шат. `value_counts()` болон `groupby()`-д суралцах нь зорилго.

**КО:** 데이터를 **그룹으로 묶어 합계·평균·건수**를 내는 분석의 핵심 단계입니다. `value_counts()`와 `groupby()`에 익숙해지는 것이 목표입니다.

### T3-1.
**МН:** Валют тус бүрийн мэдүүлгийн тоо, гарал үүслийн улс тус бүрийн мэдүүлгийн тоог тус тус гаргаарай.

**КО:** 결제통화별 신고 건수와 원산지별 신고 건수를 각각 세어 보세요.

> 💡 `df['col'].value_counts()`

In [51]:
num = df["origin_country"].value_counts(df(["currency"]))
print(num)

TypeError: 'DataFrame' object is not callable

### T3-2.
**МН:** Гарал үүслийн улс **тус бүрээр** `stat_value`-ийн нийлбэр болон дунджийг гарга.

**КО:** **원산지별** 과세가격(`stat_value`)의 합계와 평균을 구하세요.

> 💡 `df.groupby('origin_country')['stat_value'].sum()` / `.mean()`

### T3-3.
**МН:** Төлбөрийн дүнг **орон нутгийн валют (MNT)-аар хөрвүүлсэн** `value_local` шинэ багана үүсгэ. (`pay_amount` нь валютын дүн, `exch_rate` нь нэгж тутамд ногдох ханш.)

**КО:** 결제금액을 **현지통화(MNT) 기준으로 환산**한 새 컬럼 `value_local`을 만드세요. (`pay_amount`는 결제통화 금액, `exch_rate`는 1단위당 현지통화 환율.)

> 💡 `df['pay_amount'] * df['exch_rate']`

### T3-4.
**МН:** Гаалийн газар (`customs_office`) **тус бүрийн** гаалийн татвар (`duty_amount`)-ын нийлбэрийг гаргаж, их дарааллаар эхний 10-ыг үз.

**КО:** **세관(`customs_office`)별 관세액(`duty_amount`) 합계**를 구하고, 큰 순서로 상위 10개를 보세요.

> 💡 `groupby(...).sum().sort_values(ascending=False).head(10)`

### T3-5.
**МН:** Мэдүүлгийн тоо хамгийн их байсан **зуучлагч (`broker`) эхний 10**-ыг ол.

**КО:** 신고 건수가 가장 많은 **관세사(`broker`) 상위 10곳**을 찾으세요.

> 💡 `value_counts().head(10)`

## Part 4. Цаг хугацааны хандлага ба пивот / 시계열 기초 & 피벗

**МН:** Огноог ашиглан **цаг хугацааны хандлагыг** хараад, **пивот хүснэгтээр** хоёр тэнхлэгийг огтлолцуулан нэгтгэнэ. (Part 1-д үүсгэсэн `month` баганыг ашиглана.)

**КО:** 날짜를 활용해 **시간에 따른 추세**를 보고, **피벗 테이블**로 두 축을 교차 집계합니다. (Part 1에서 만든 `month` 컬럼 사용.)

### T4-1.
**МН:** Сар тус бүрийн мэдүүлгийн тоог гарга.

**КО:** 월별 신고 건수를 구하세요.

> 💡 `df['month'].value_counts().sort_index()`

### T4-2.
**МН:** **Өдөр тус бүрийн** мэдүүлгийн тоог гарга.

**КО:** **일별** 신고 건수 추세를 구하세요.

> 💡 `df.groupby('decl_date').size()`

### T4-3.
**МН:** **Сар × гарал үүслийн улс** огтлолцол хүснэгт үүсгэ (мөр=month, багана=origin_country, утга=тоо). Улс хэт олон тул JP/CN/KR/RU/US-ийг л сонго.

**КО:** **월 × 원산지** 교차표를 만드세요 (행=month, 열=origin_country, 값=건수). 원산지는 JP/CN/KR/RU/US 만 골라서.

> 💡 `pd.pivot_table(df, index='month', columns='origin_country', values='decl_no', aggfunc='count')`